name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - 'year-[0-9]+'

jobs:
  build:
    if: startsWith(github.ref, 'refs/heads/year-') || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract branch name
        id: extract-branch
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Build and push Docker image for main branch
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            atyasu/docker-texlive-ja-addition-fonts:latest
          platforms: linux/amd64,linux/arm64

      - name: Build and push Docker image for year-* branches
        if: startsWith(github.ref, 'refs/heads/year-')
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            atyasu/docker-texlive-ja-addition-fonts:${{ env.BRANCH_NAME }}
          platforms: linux/amd64,linux/arm64

